import type { Lead } from "./supabase";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

export const SAMPLE_LEADS: Lead[] = [
  {
    id: "1",
    name: "Marcus Thompson",
    email: "marcus@apextalent.com",
    phone: "+1 (312) 555-0198",
    company: "Apex Talent Group",
    tier_interest: "Enterprise",
    message: "We're managing 300+ placements and drowning in manual work. Need full automation.",
    score: 100,
    status: "Closed Won",
    notes: [
      { id: "n1", text: "Initial call went very well. They're ready to move fast.", author: "Admin", created_at: daysAgo(20) },
      { id: "n2", text: "Sent proposal. $2,500/mo Enterprise. Accepted same day.", author: "Admin", created_at: daysAgo(18) },
    ],
    created_at: daysAgo(25),
    updated_at: daysAgo(18),
  },
  {
    id: "2",
    name: "Priya Sharma",
    email: "priya@meridianprop.com",
    phone: "+1 (415) 555-0234",
    company: "Meridian Properties",
    tier_interest: "Growth",
    message: "Need content automation and better lead tracking.",
    score: 80,
    status: "Closed Won",
    notes: [
      { id: "n3", text: "Qualified. Moved to Growth plan. Great fit.", author: "Admin", created_at: daysAgo(15) },
    ],
    created_at: daysAgo(22),
    updated_at: daysAgo(15),
  },
  {
    id: "3",
    name: "James Calloway",
    email: "james@brightlinecommerce.com",
    phone: "+1 (646) 555-0112",
    company: "Brightline Commerce",
    tier_interest: "Enterprise",
    message: "Rapid growth creating operational chaos. Need unified analytics and CS automation.",
    score: 100,
    status: "Proposal",
    notes: [
      { id: "n4", text: "Strong interest. CFO needs to review numbers.", author: "Admin", created_at: daysAgo(5) },
    ],
    created_at: daysAgo(12),
    updated_at: daysAgo(5),
  },
  {
    id: "4",
    name: "Sofia Reyes",
    email: "sofia@peakadvisory.com",
    phone: "+1 (305) 555-0087",
    company: "Peak Advisory",
    tier_interest: "Growth",
    message: "Want to automate client portal and invoicing.",
    score: 80,
    status: "Qualified",
    notes: [
      { id: "n5", text: "Demo scheduled for next week.", author: "Admin", created_at: daysAgo(3) },
    ],
    created_at: daysAgo(9),
    updated_at: daysAgo(3),
  },
  {
    id: "5",
    name: "Derek Owens",
    email: "derek@vantagemedia.co",
    phone: "+1 (713) 555-0045",
    company: "Vantage Media",
    tier_interest: "Foundation",
    message: "Starting out, want the basics set up right.",
    score: 60,
    status: "Contacted",
    notes: [],
    created_at: daysAgo(7),
    updated_at: daysAgo(6),
  },
  {
    id: "6",
    name: "Natalie Cruz",
    email: "natalie@clearpath.finance",
    phone: "",
    company: "Clearpath Finance",
    tier_interest: "Growth",
    message: "Looking for lead nurture + billing automation.",
    score: 70,
    status: "New",
    notes: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    id: "7",
    name: "Ray Patel",
    email: "ray@summitops.io",
    phone: "+1 (408) 555-0321",
    company: "Summit Operations",
    tier_interest: "Enterprise",
    message: "Need white-label platform for our clients. Multi-team setup.",
    score: 100,
    status: "Contacted",
    notes: [
      { id: "n6", text: "High priority. Enterprise white-label is a perfect fit.", author: "Admin", created_at: daysAgo(1) },
    ],
    created_at: daysAgo(4),
    updated_at: daysAgo(1),
  },
  {
    id: "8",
    name: "Amanda Foster",
    email: "amanda@fosterco.com",
    phone: "",
    company: "",
    tier_interest: "Foundation",
    message: "Just exploring options for my small business.",
    score: 40,
    status: "New",
    notes: [],
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "9",
    name: "Chris Navarro",
    email: "chris@navarro-group.com",
    phone: "+1 (503) 555-0177",
    company: "Navarro Group",
    tier_interest: "Growth",
    message: "Referred by Priya Sharma. Want the same setup.",
    score: 80,
    status: "New",
    notes: [],
    created_at: daysAgo(0.5),
    updated_at: daysAgo(0.5),
  },
  {
    id: "10",
    name: "Lauren Kim",
    email: "lauren@lkstrategy.com",
    phone: "+1 (212) 555-0099",
    company: "LK Strategy Partners",
    tier_interest: "Enterprise",
    message: "Multi-office firm, 20 team members. Need roles and custom workflows.",
    score: 100,
    status: "Closed Lost",
    notes: [
      { id: "n7", text: "Chose a competitor. Pricing was the issue.", author: "Admin", created_at: daysAgo(10) },
    ],
    created_at: daysAgo(18),
    updated_at: daysAgo(10),
  },
];
